### ISSUE TITLE
Cams.py error

### ISSUE THREAD

**Issue by JohnOfCode** [random-robbie/My-Shodan-Scripts#1]
Hi,

When i Try to use the cams.py It returns the error: 

'module' object has no attribute 'TimeoutExpired'
Error: 'module' object has no attribute 'TimeoutExpired

**Comment by random-robbie** [comment]
Hi,
you need to use python 3 for this to work.

**Comment by JohnOfCode** [comment]
I'm using the last version of Python. I have both 2 and 3 installed and, even if I put this code -
 "#!/usr/bin/env python3"  - at first line of the script It returns the error.

**Comment by random-robbie** [comment]
[![Screen_Shot_2018-03-05_at_23.55.59.png](https://s17.postimg.org/rjcbhntpr/Screen_Shot_2018-03-05_at_23.55.59.png)](https://postimg.org/image/5k5wugcvf/)

Working fine for me when i do

```
python3 cams.py
```

Running on 

```
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
```
